version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - 5433:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data 

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:anomaly_webserver
    container_name: airflow_webserver
    depends_on:
      - postgres

    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: somethingsecret
    command: >
      bash -c "
        airflow db init && 
        airflow users create --username egemen --password egemen --firstname Egemen --lastname User --role Admin --email egedalgic@gmail.com &&
        airflow webserver
      "

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:anomaly_scheduler
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: somethingsecret
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
    command: >
      bash -c "
        sleep 10 &&
        airflow db init &&
        airflow scheduler
      "   

volumes:
  postgres-db-volume:
